import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/exports";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.svg',
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
        <body className={`${inter.className} bg-[#16161E] animate-slide-in-top`}>
        <Header/>
        {children}
        </body>
        </html>
    );
}
