import Image from "next/image";
import {InputChat, BackgroundRadial, BackgroundLinear, BackgroundComment} from "@/components/exports";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
}
export default function Home() {
    return (
        <main className="relative w-full h-[calc(100vh-8rem)] overflow-hidden">
            <BackgroundComment/>
            <BackgroundRadial/>
            <BackgroundLinear/>
            <div className="absolute h-full flex items-center justify-center w-full mb-40 z-50">
                <Image alt="logo" src="/static/images/logo.png" width="250" height="250"/>
            </div>
            <div className="absolute bottom-0 w-full z-50 flex justify-center italic">
                <InputChat disabled={true}/>
            </div>
        </main>
    );
}
